[versions]
coreKtxVersion = "1.7.0"
datastoreVersion = "1.2.0"
detektFormattingVersion = "1.23.8"
firebaseAnalyticsKtxVersion = "22.5.0"
firebaseConfigKtxVersion = "22.1.2"
googleServicesVersion = "4.4.4"
gradleVersion = "8.13.2"
hiltCompilerVersion = "1.3.0"
hiltWorkVersion = "1.3.0"
kotlinVersion = "2.2.0"
kspVersion = "2.2.0-2.0.2"
ktlintGradleVersion = "12.1.2"
mockwebserverVersion = "5.3.2"
navigationSafeArgsGradlePluginVersion = "2.9.6"
protobufJavaliteVersion = "4.33.3"
retrofitVersion = "3.0.0"
retrofitMoshiConverterVersion = "3.0.0"
moshiVersion = "1.15.2"
robolectricVersion = "4.16"
roomVersion = "2.8.4"
interceptorVersion = "5.3.2"
glideVersion = "5.0.5"
hiltVersion = "2.57.2"
jUnitXVersion = "1.3.0"
testRunnerVersion = "1.7.0"
truthVersion = "1.4.5"
lottieVersion = "6.7.1"
pagingVersion = "3.3.6"
detektVersion = "1.23.8"
spotlessVersion = "7.0.0"
timberVersion = "5.0.1"
dokkaVersion = "2.0.0"
accompanistVersion = "0.36.0"
glideComposeVersion = "1.0.0-beta08"
material3Version = "1.4.0"
composeActivityVersion = "1.12.2"
hiltComposeVersion = "1.3.0"
constraintLayoutComposeVersion = "1.1.1"
pagingComposeVersion = "3.3.6"
composeNavigationVersion = "2.9.6"
androidxComposeBom = "2026.01.00"
composeLifecycleVersion = "2.10.0"
espresso-core = "3.7.0"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.4.1"
profileInstallerVersion = "1.4.1"
core-ktx = "1.17.0"
junit = "4.13.2"
mockkVersion = "1.14.7"
uiTestManifestVersion = "1.10.1"
uiTestJunit4Version = "1.10.1"
workRuntimeKtxVersion = "2.11.0"
workRuntimeVersion = "2.11.0"
paparazzi = "1.3.5"
androidx-appcompat-appcompat = "1.7.1"
com-google-android-material-material = "1.13.0"

[libraries]
androidx-core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtxVersion" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastoreVersion" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompilerVersion" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWorkVersion" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePluginVersion" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifestVersion" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4Version" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtxVersion" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntimeVersion" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintLayoutComposeVersion" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektFormattingVersion" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtxVersion" }
firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx", version.ref = "firebaseConfigKtxVersion" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServicesVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltVersion" }
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlintGradleVersion" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserverVersion" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavaliteVersion" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofitMoshiConverterVersion" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshiVersion" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshiVersion" }
okhttp3-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "interceptorVersion" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltVersion" }
hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hiltVersion" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltComposeVersion" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectricVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glideVersion" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glideVersion" }
glide-compose = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glideComposeVersion" }

lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieVersion" }
paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "pagingVersion" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingComposeVersion" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timberVersion" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui-tooling" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivityVersion" }
accompanist-system-ui-controller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanistVersion" }
accompanist-theme-adapter-material = { group = "com.google.accompanist", name = "accompanist-themeadapter-material", version.ref = "accompanistVersion" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "composeLifecycleVersion" }

material3-compose = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Version" }
material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3Version" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
profile-installer = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileInstallerVersion" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version = "24.1.2" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
junitx = { group = "androidx.test.ext", name = "junit", version.ref = "jUnitXVersion" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunnerVersion" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truthVersion" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion" }
mochito = { group = "org.mockito", name = "mockito-core", version = "5.21.0" }
turbine = { group = "app.cash.turbine", name = "turbine", version = "1.2.1" }
kotlinx-coroutine-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.10.2" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat-appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "com-google-android-material-material" }
paparazzi = { module = "app.cash.paparazzi:paparazzi", version.ref = "paparazzi" }
#build-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
#hilt-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }

[plugins]
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }

